# Generated by Django 4.2.4 on 2023-09-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_subscribe_matn_email_alter_subscribe_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='matn_email',
            new_name='matn',
        ),
    ]
