# Generated by Django 4.2.4 on 2023-08-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edu_nameUni', models.CharField(max_length=30)),
                ('Edu_datestart', models.CharField(max_length=30)),
                ('Edu_datefinish', models.CharField(max_length=30)),
                ('Edu_majarName', models.CharField(max_length=60)),
                ('Edu_des', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exp_nameCo', models.CharField(max_length=30)),
                ('Exp_date_start', models.CharField(max_length=30)),
                ('Exp_date_finish', models.CharField(max_length=30)),
                ('Exp_title', models.CharField(max_length=60)),
                ('Exp_des', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_name', models.CharField(max_length=30)),
                ('Pro_Coname', models.CharField(max_length=30)),
                ('Pro_date', models.CharField(max_length=30)),
                ('Pro_Subject', models.CharField(max_length=200)),
                ('Pro_des', models.CharField(max_length=600)),
            ],
        ),
    ]
