# Generated by Django 4.2.4 on 2023-09-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_name', models.CharField(max_length=30)),
                ('Service_Coname', models.CharField(max_length=30)),
                ('Service_date', models.CharField(max_length=30)),
                ('Service_Subject', models.CharField(max_length=200)),
                ('Service_des', models.CharField(max_length=600)),
            ],
        ),
    ]
