# Generated by Django 4.2.4 on 2023-09-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_edu_edu_nameuni'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='exp',
            name='Exp_date_finish',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='exp',
            name='Exp_date_start',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='exp',
            name='Exp_des',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='exp',
            name='Exp_nameCo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='exp',
            name='Exp_title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
